export interface Language {
  code: string; // ISO code (e.g., 'bn', 'hi', 'en')
  name: string; // English name (e.g., 'Bengali')
  nativeName: string; // Native script name (e.g., 'বাংলা')
  speechLocale: string; // BCP-47 locale (e.g., 'bn-IN')
  script: string;
}

export const INDIAN_LANGUAGES: Language[] = [
  { code: 'en', name: 'English', nativeName: 'English', speechLocale: 'en-IN', script: 'Latin' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', speechLocale: 'hi-IN', script: 'Devanagari' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', speechLocale: 'bn-IN', script: 'Bengali' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', speechLocale: 'te-IN', script: 'Telugu' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', speechLocale: 'mr-IN', script: 'Devanagari' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', speechLocale: 'ta-IN', script: 'Tamil' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو', speechLocale: 'ur-IN', script: 'Arabic' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', speechLocale: 'gu-IN', script: 'Gujarati' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', speechLocale: 'kn-IN', script: 'Kannada' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ', speechLocale: 'or-IN', script: 'Odia' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', speechLocale: 'ml-IN', script: 'Malayalam' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', speechLocale: 'pa-IN', script: 'Gurmukhi' },
  { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া', speechLocale: 'as-IN', script: 'Bengali-Assamese' },
  { code: 'mai', name: 'Maithili', nativeName: 'मैथिली', speechLocale: 'hi-IN', script: 'Devanagari' },
  { code: 'sat', name: 'Santali', nativeName: 'ᱥᱟᱱᱛᱟᱲᱤ / संथाली', speechLocale: 'hi-IN', script: 'Ol Chiki' },
  { code: 'ks', name: 'Kashmiri', nativeName: 'कॉशुर / کٲشُر', speechLocale: 'ur-IN', script: 'Perso-Arabic' },
  { code: 'ne', name: 'Nepali', nativeName: 'नेपाली', speechLocale: 'ne-NP', script: 'Devanagari' },
  { code: 'kok', name: 'Konkani', nativeName: 'कोंकणी', speechLocale: 'mr-IN', script: 'Devanagari' },
  { code: 'sd', name: 'Sindhi', nativeName: 'سنڌي / सिन्धी', speechLocale: 'ur-IN', script: 'Arabic' },
  { code: 'doi', name: 'Dogri', nativeName: 'डोगरी', speechLocale: 'hi-IN', script: 'Devanagari' },
  { code: 'mni', name: 'Manipuri (Meitei)', nativeName: 'মৈতৈলোন্', speechLocale: 'bn-IN', script: 'Meetei Mayek' },
  { code: 'brx', name: 'Bodo', nativeName: 'बड़ो', speechLocale: 'hi-IN', script: 'Devanagari' },
  { code: 'sa', name: 'Sanskrit', nativeName: 'संस्कृतम्', speechLocale: 'hi-IN', script: 'Devanagari' },
];

export interface TranslationDictionary {
  appTitle: string;
  appSubtitle: string;
  presentTab: string;
  pastTab: string;
  liveStatus: string;
  staleStatus: string;
  activeAlerts: string;
  alertTypes: string;
  useMyLocation: string;
  checkAnotherLocation: string;
  searchLocationPlaceholder: string;
  nearMeMode: string;
  indiaMode: string;
  officialInstructionTitle: string;
  plainSummaryTitle: string;
  viewDetails: string;
  dismiss: string;
  share: string;
  copySummary: string;
  searchDisastersPlaceholder: string;
  historicalResearchTitle: string;
  compareEvents: string;
  aiAssistant: string;
  originalReports: string;
  timelineTitle: string;
  whatHappenedTitle: string;
  impactTitle: string;
  responseTitle: string;
  sourceAssessmentTitle: string;
  conflictingReportsTitle: string;
  noAlertsNearby: string;
  noActiveAlerts: string;
  currentNewsTitle: string;
  voiceAssistantTitle: string;
  voiceListening: string;
  voiceSpeakPrompt: string;
  searchLanguagePlaceholder: string;
  indiaMapTitle?: string;
  askAIAssistant?: string;
  pastDisastersTitle?: string;
  searchDisasterPlaceholder?: string;
  compareNow?: string;
}

export const TRANSLATIONS: Record<string, TranslationDictionary> = {
  en: {
    appTitle: "Disaster Intelligence Platform",
    appSubtitle: "Official Alerts • Geospatial Context • Grounded Research",
    presentTab: "PRESENT (Live Situation)",
    pastTab: "PAST (Historical Research)",
    liveStatus: "OFFICIAL FEED LIVE",
    staleStatus: "CACHED SNAPSHOT",
    activeAlerts: "Active Official Alerts",
    alertTypes: "Alert Categories",
    useMyLocation: "Use My Location",
    checkAnotherLocation: "Check Another Location",
    searchLocationPlaceholder: "Search Indian city, district or village...",
    nearMeMode: "NEAR ME",
    indiaMode: "ALL INDIA",
    officialInstructionTitle: "Official Instructions",
    plainSummaryTitle: "Situation Summary",
    viewDetails: "View Details",
    dismiss: "Dismiss",
    share: "Share Warning",
    copySummary: "Copy Summary",
    searchDisastersPlaceholder: "Search historical disasters, events or locations (e.g., Cyclone Fani, Kerala Floods)...",
    historicalResearchTitle: "Historical Disaster Research",
    compareEvents: "Compare Events",
    aiAssistant: "AI Research Assistant",
    originalReports: "Original Reports & Media",
    timelineTitle: "Chronological Timeline",
    whatHappenedTitle: "What Happened",
    impactTitle: "Human & Infrastructure Impact",
    responseTitle: "Government & Rescue Response",
    sourceAssessmentTitle: "Source Assessment",
    conflictingReportsTitle: "Conflicting Reports",
    noAlertsNearby: "No active alerts detected near your location.",
    noActiveAlerts: "No active official alerts currently in feed.",
    currentNewsTitle: "Verified Current News (72h Gate)",
    voiceAssistantTitle: "Multilingual Voice Assistant",
    voiceListening: "Listening in your language...",
    voiceSpeakPrompt: "Speak or ask anything in any Indian language",
    searchLanguagePlaceholder: "Search language (English or script)...",
  },
  hi: {
    appTitle: "आपदा सूचना एवं अनुसंधान मंच",
    appSubtitle: "आधिकारिक अलर्ट • भू-स्थानिक संदर्भ • प्रामाणिक शोध",
    presentTab: "वर्तमान (सक्रिय आपदाएं)",
    pastTab: "अतीत (ऐतिहासिक शोध)",
    liveStatus: "लाइव आधिकारिक अलर्ट",
    staleStatus: "कैश डेटा (सत्यापित)",
    activeAlerts: "सक्रिय आधिकारिक अलर्ट",
    alertTypes: "आपदा श्रेणियां",
    useMyLocation: "मेरा स्थान उपयोग करें",
    checkAnotherLocation: "अन्य स्थान की जांच करें",
    searchLocationPlaceholder: "शहर, जिला या गांव खोजें...",
    nearMeMode: "मेरे निकट",
    indiaMode: "अखिल भारतीय",
    officialInstructionTitle: "आधिकारिक निर्देश",
    plainSummaryTitle: "स्थिति सारांश",
    viewDetails: "विवरण देखें",
    dismiss: "हटाएं",
    share: "चेतावनी साझा करें",
    copySummary: "सारांश कॉपी करें",
    searchDisastersPlaceholder: "ऐतिहासिक आपदाएं या घटनाएं खोजें (उदा. फानी चक्रवात, केरल बाढ़)...",
    historicalResearchTitle: "ऐतिहासिक आपदा अनुसंधान",
    compareEvents: "घटनाओं की तुलना करें",
    aiAssistant: "एआई शोध सहायक",
    originalReports: "मूल समाचार और रिपोर्ट",
    timelineTitle: "घटनाक्रम (टाइमलाइन)",
    whatHappenedTitle: "क्या हुआ था",
    impactTitle: "मानवीय एवं ढांचागत प्रभाव",
    responseTitle: "सरकारी एवं राहत प्रतिक्रिया",
    sourceAssessmentTitle: "स्रोत विश्वसनीयता",
    conflictingReportsTitle: "विरोधाभासी रिपोर्टें",
    noAlertsNearby: "आपके स्थान के पास कोई सक्रिय अलर्ट नहीं है।",
    noActiveAlerts: "वर्तमान में कोई सक्रिय चेतावनी नहीं है।",
    currentNewsTitle: "सत्यापित हालिया समाचार (72 घंटे)",
    voiceAssistantTitle: "बहुभाषी वॉइस सहायक",
    voiceListening: "आपकी भाषा में सुन रहे हैं...",
    voiceSpeakPrompt: "किसी भी भारतीय भाषा में बोलें या पूछें",
    searchLanguagePlaceholder: "भाषा खोजें (अंग्रेजी या लिपि)...",
  },
  bn: {
    appTitle: "দুর্যোগ তথ্য ও গবেষণা প্ল্যাটফর্ম",
    appSubtitle: "সরকারি সতর্কতা • ভূ-স্থানিক বুদ্ধিমত্তা • তথ্যভিত্তিক গবেষণা",
    presentTab: "বর্তমান (লাইভ পরিস্থিতি)",
    pastTab: "অতীত (ঐতিহাসিক গবেষণা)",
    liveStatus: "লাইভ সরকারি তথ্য",
    staleStatus: "ক্যাশ ডেটা",
    activeAlerts: "সক্রিয় সরকারি সতর্কতা",
    alertTypes: "দুর্যোগের ধরন",
    useMyLocation: "আমার অবস্থান ব্যবহার করুন",
    checkAnotherLocation: "অন্য স্থান পরীক্ষা করুন",
    searchLocationPlaceholder: "শহর, জেলা বা স্থান অনুসন্ধান করুন...",
    nearMeMode: "আমার কাছে",
    indiaMode: "সমগ্র ভারত",
    officialInstructionTitle: "সরকারি নির্দেশাবলী",
    plainSummaryTitle: "পরিস্থিতি সারসংক্ষেপ",
    viewDetails: "বিস্তারিত দেখুন",
    dismiss: "বাতিল করুন",
    share: "সতর্কতা শেয়ার করুন",
    copySummary: "সারসংক্ষেপ কপি করুন",
    searchDisastersPlaceholder: "ঐতিহাসিক দুর্যোগ খুঁজুন (যেমন: ঘূর্ণিঝড় ফণী, কেরালা বন্যা)...",
    historicalResearchTitle: "ঐতিহাসিক দুর্যোগ গবেষণা",
    compareEvents: "ঘটনা তুলনা করুন",
    aiAssistant: "এআই গবেষণা সহকারী",
    originalReports: "মূল প্রতিবেদন ও সংবাদ",
    timelineTitle: "ঘটনাপঞ্জি (টাইমলাইন)",
    whatHappenedTitle: "কী ঘটেছিল",
    impactTitle: "মানবিক ও অবকাঠামোগত ক্ষয়ক্ষতি",
    responseTitle: "সরকারি ত্রাণ ও উদ্ধার কাজ",
    sourceAssessmentTitle: "উৎস নির্ভরযোগ্যতা",
    conflictingReportsTitle: "পরস্পরবিরোধী রিপোর্ট",
    noAlertsNearby: "আপনার এলাকার কাছে কোনো সক্রিয় সতর্কতা নেই।",
    noActiveAlerts: "বর্তমানে কোনো সক্রিয় সতর্কতা নেই।",
    currentNewsTitle: "যাচাইকৃত সাম্প্রতিক সংবাদ (৭২ ঘণ্টা)",
    voiceAssistantTitle: "বহুভাষিক ভয়েস সহকারী",
    voiceListening: "আপনার ভাষায় শুনছি...",
    voiceSpeakPrompt: "যেকোনো ভারতীয় ভাষায় কথা বলুন বা জিজ্ঞাসা করুন",
    searchLanguagePlaceholder: "ভাষা খুঁজুন (ইংরেজি বা বাংলা লিপিতে)...",
  },
  ta: {
    appTitle: "பேரிடர் தகவல் தளம்",
    appSubtitle: "அதிகாரப்பூர்வ எச்சரிக்கைகள் • புவிசார் சூழல் • ஆதார அடிப்படையிலான ஆய்வு",
    presentTab: "தற்போதைய நிலை (நேரலை)",
    pastTab: "கடந்த கால ஆய்வு (வரலாறு)",
    liveStatus: "நேரலை எச்சரிக்கை",
    staleStatus: "சேமிக்கப்பட்ட தகவல்",
    activeAlerts: "செயலில் உள்ள எச்சரிக்கைகள்",
    alertTypes: "பேரிடர் வகைகள்",
    useMyLocation: "எனது இருப்பிடத்தைப் பயன்படுத்து",
    checkAnotherLocation: "வேறு இடத்தை சரிபார்க்கவும்",
    searchLocationPlaceholder: "நகரம், மாவட்டம் அல்லது கிராமத்தை தேடுங்கள்...",
    nearMeMode: "என் அருகில்",
    indiaMode: "இந்தியா முழுவதும்",
    officialInstructionTitle: "அதிகாரப்பூர்வ வழிகாட்டுதல்கள்",
    plainSummaryTitle: "நிலைமை சுருக்கம்",
    viewDetails: "விவரங்களைக் காண்க",
    dismiss: "விலக்கு",
    share: "பகிரவும்",
    copySummary: "சுருக்கத்தை நகலெடு",
    searchDisastersPlaceholder: "வரலாற்றுப் பேரிடர்களைத் தேடுங்கள் (எ.கா. ஃபானி புயல்)...",
    historicalResearchTitle: "வரலாற்றுப் பேரிடர் ஆராய்ச்சி",
    compareEvents: "ஒப்பிடுக",
    aiAssistant: "AI ஆராய்ச்சி உதவியாளர்",
    originalReports: "அசல் அறிக்கைகள்",
    timelineTitle: "காலவரிசை",
    whatHappenedTitle: "என்ன நடந்தது",
    impactTitle: "பாதிப்புகள்",
    responseTitle: "அரசு நிவாரணப் பணிகள்",
    sourceAssessmentTitle: "ஆதார மதிப்பீடு",
    conflictingReportsTitle: "முரண்பட்ட அறிக்கைகள்",
    noAlertsNearby: "உங்கள் பகுதிக்கு அருகில் எச்சரிக்கைகள் இல்லை.",
    noActiveAlerts: "செயலில் உள்ள எச்சரிக்கைகள் எதுவும் இல்லை.",
    currentNewsTitle: "சரிபார்க்கப்பட்ட சமீபத்திய செய்திகள்",
    voiceAssistantTitle: "குரல் உதவியாளர்",
    voiceListening: "கேட்கிறது...",
    voiceSpeakPrompt: "எந்த இந்திய மொழியிலும் பேசுங்கள்",
    searchLanguagePlaceholder: "மொழியைத் தேடுங்கள்...",
  },
  te: {
    appTitle: "విపత్తు సమాచార వేదిక",
    appSubtitle: "అధికారిక హెచ్చరికలు • భౌగోళిక సమాచారం • పరిశోధన",
    presentTab: "ప్రస్తుత స్థితి (లైవ్)",
    pastTab: "గత చరిత్ర (పరిశోధన)",
    liveStatus: "ప్రత్యక్ష సమాచారం",
    staleStatus: "కాష్ సమాచారం",
    activeAlerts: "యాక్టివ్ హెచ్చరికలు",
    alertTypes: "విపత్తు రకాలు",
    useMyLocation: "నా లొకేషన్ ఉపయోగించండి",
    checkAnotherLocation: "మరో ప్రాంతాన్ని తనిఖీ చేయండి",
    searchLocationPlaceholder: "నగరం లేదా జిల్లాను శోధించండి...",
    nearMeMode: "నా దగ్గర",
    indiaMode: "భారతదేశం అంతటా",
    officialInstructionTitle: "అధికారిక సూచనలు",
    plainSummaryTitle: "పరిస్థితి సారాంశం",
    viewDetails: "వివరాలు చూడండి",
    dismiss: "రద్దు చేయి",
    share: "హెచ్చరికను పంచుకోండి",
    copySummary: "సారాంశాన్ని కాపీ చేయండి",
    searchDisastersPlaceholder: "చారిత్రక విపత్తులను శోధించండి...",
    historicalResearchTitle: "చారిత్రక విపత్తు పరిశోధన",
    compareEvents: "ఈవెంట్లను సరిపోల్చండి",
    aiAssistant: "AI సహాయకుడు",
    originalReports: "అసలు నివేదికలు",
    timelineTitle: "టైమ్‌లైన్",
    whatHappenedTitle: "ఏమి జరిగింది",
    impactTitle: "ప్రభావం మరియు నష్టం",
    responseTitle: "ప్రభుత్వ ప్రతిస్పందన",
    sourceAssessmentTitle: "మూలాల ధృవీకరణ",
    conflictingReportsTitle: "విరుద్ధ నివేదికలు",
    noAlertsNearby: "మీ ప్రాంతంలో హెచ్చరికలు లేవు.",
    noActiveAlerts: "యాక్టివ్ హెచ్చరికలు ఏవీ లేవు.",
    currentNewsTitle: "తాజా వార్తలు",
    voiceAssistantTitle: "వాయిస్ అసిస్టెంట్",
    voiceListening: "వింటోంది...",
    voiceSpeakPrompt: "భారతీయ భాషలో మాట్లాడండి",
    searchLanguagePlaceholder: "భాషను శోధించండి...",
  },
  mr: {
    appTitle: "आपत्ती माहिती व संशोधन व्यासपीठ",
    appSubtitle: "अधिकृत इशारे • भौगोलिक संदर्भ • पुरावा-आधारित संशोधन",
    presentTab: "सध्याची स्थिती (लाईव्ह)",
    pastTab: "भूतकाळ (ऐतिहासिक संशोधन)",
    liveStatus: "लाईव्ह अधिकृत डेटा",
    staleStatus: "कॅश डेटा",
    activeAlerts: "सक्रिय अधिकृत इशारे",
    alertTypes: "आपत्ती प्रकार",
    useMyLocation: "माझे स्थान वापरा",
    checkAnotherLocation: "इतर स्थान तपासा",
    searchLocationPlaceholder: "शहर, जिल्हा किंवा गाव शोधा...",
    nearMeMode: "माझ्या जवळ",
    indiaMode: "संपूर्ण भारत",
    officialInstructionTitle: "अधिकृत सूचना",
    plainSummaryTitle: "परिस्थितीचा सारांश",
    viewDetails: "तपशील पहा",
    dismiss: "बंद करा",
    share: "इशारा शेअर करा",
    copySummary: "सारांश कॉपी करा",
    searchDisastersPlaceholder: "ऐतिहासिक आपत्ती शोधा...",
    historicalResearchTitle: "ऐतिहासिक आपत्ती संशोधन",
    compareEvents: "तुलना करा",
    aiAssistant: "एआय संशोधन सहाय्यक",
    originalReports: "मूळ बातम्या व अहवाल",
    timelineTitle: "घटनाक्रम (टाइमलाइन)",
    whatHappenedTitle: "काय घडले होते",
    impactTitle: "मानवी व पायाभूत नुकसान",
    responseTitle: "शासकीय मदत व बचाव कार्य",
    sourceAssessmentTitle: "स्रोत विश्वसनीयता",
    conflictingReportsTitle: "परस्परविरोधी अहवाल",
    noAlertsNearby: "तुमच्या परिसरात कोणताही इशारा नाही.",
    noActiveAlerts: "सध्या कोणताही सक्रिय इशारा नाही.",
    currentNewsTitle: "सत्यापित ताज्या बातम्या",
    voiceAssistantTitle: "व्हॉइस सहाय्यक",
    voiceListening: "ऐकत आहे...",
    voiceSpeakPrompt: "कोणत्याही भारतीय भाषेत बोला",
    searchLanguagePlaceholder: "भाषा शोधा...",
  },
  or: {
    appTitle: "ବିପର୍ଯ୍ୟୟ ସୂଚନା ଓ ଅନୁସନ୍ଧାନ ମଞ୍ଚ",
    appSubtitle: "ସରକାରୀ ସତର୍କତା • ଭୌଗୋଳିକ ସୂଚନା • ତଥ୍ୟଭିତ୍ତିକ ଗବେଷଣା",
    presentTab: "ବର୍ତ୍ତମାନ (ଲାଇଭ ସ୍ଥିତି)",
    pastTab: "ଅତୀତ (ଐତିହାସିକ ଗବେଷଣା)",
    liveStatus: "ଲାଇଭ ସରକାରୀ ସୂଚନା",
    staleStatus: "କ୍ୟାସ୍ ତଥ୍ୟ",
    activeAlerts: "ସକ୍ରିୟ ସରକାରୀ ସତର୍କତା",
    alertTypes: "ବିପର୍ଯ୍ୟୟ ବର୍ଗ",
    useMyLocation: "ମୋର ସ୍ଥାନ ବ୍ୟବହାର କରନ୍ତୁ",
    checkAnotherLocation: "ଅନ୍ୟ ସ୍ଥାନ ଯାଞ୍ଚ କରନ୍ତୁ",
    searchLocationPlaceholder: "ସହର, ଜିଲ୍ଲା ବା ଗ୍ରାମ ଖୋଜନ୍ତୁ...",
    nearMeMode: "ମୋ ନିକଟରେ",
    indiaMode: "ସମଗ୍ର ଭାରତ",
    officialInstructionTitle: "ସରକାରୀ ନିର୍ଦ୍ଦେଶାବଳୀ",
    plainSummaryTitle: "ସ୍ଥିତି ସାରାଂଶ",
    viewDetails: "ବିବରଣୀ ଦେଖନ୍ତୁ",
    dismiss: "ଅଣଦେଖା କରନ୍ତୁ",
    share: "ସତର୍କତା ସେୟାର କରନ୍ତୁ",
    copySummary: "ସାରାଂଶ କପି କରନ୍ତୁ",
    searchDisastersPlaceholder: "ଐତିହାସିକ ବିପର୍ଯ୍ୟୟ ଖୋଜନ୍ତୁ (ଯଥା: ଫନି ବାତ୍ୟା)...",
    historicalResearchTitle: "ଐତିହାସିକ ବିପର୍ଯ୍ୟୟ ଗବେଷଣା",
    compareEvents: "ତୁଳନା କରନ୍ତୁ",
    aiAssistant: "AI ଗବେଷଣା ସହାୟକ",
    originalReports: "ମୂଳ ଖବର ଓ ରିପୋର୍ଟ",
    timelineTitle: "ଘଟଣାକ୍ରମ (ଟାଇମଲାଇନ୍)",
    whatHappenedTitle: "କଣ ଘଟିଥିଲା",
    impactTitle: "ମାନବୀୟ ଓ ଭିତ୍ତିଭୂମି କ୍ଷୟକ୍ଷତି",
    responseTitle: "ସରକାରୀ ଓ ରିଲିଫ ପ୍ରତିକ୍ରିୟା",
    sourceAssessmentTitle: "ଉତ୍ସ ବିଶ୍ୱସନୀୟତା",
    conflictingReportsTitle: "ପରସ୍ପର ବିରୋଧୀ ରିପୋର୍ଟ",
    noAlertsNearby: "ଆପଣଙ୍କ ଅଞ୍ଚଳ ନିକଟରେ କୌଣସି ସକ୍ରିୟ ସତର୍କତା ନାହିଁ।",
    noActiveAlerts: "ବର୍ତ୍ତମାନ କୌଣସି ସକ୍ରିୟ ସତର୍କତା ନାହିଁ।",
    currentNewsTitle: "ସତ୍ୟାପିତ ସାମ୍ପ୍ରତିକ ଖବର (୭୨ ଘଣ୍ଟା)",
    voiceAssistantTitle: "ବହୁଭାଷୀ ଭଏସ୍ ସହାୟକ",
    voiceListening: "ଶୁଣୁଛି...",
    voiceSpeakPrompt: "ଓଡ଼ିଆ କିମ୍ବା ଅନ୍ୟ ଭାରତୀୟ ଭାଷାରେ କୁହନ୍ତୁ",
    searchLanguagePlaceholder: "ଭାଷା ଖୋଜନ୍ତୁ...",
  },
};

export function getTranslation(langCode: string): TranslationDictionary {
  const base = TRANSLATIONS[langCode] || TRANSLATIONS.en;
  return {
    ...TRANSLATIONS.en,
    ...base,
    indiaMapTitle: base.indiaMapTitle || 'All India Disaster Live Map (Official SACHET)',
    askAIAssistant: base.askAIAssistant || base.aiAssistant || 'Ask AI Assistant',
    pastDisastersTitle: base.pastDisastersTitle || base.historicalResearchTitle || 'Historical Disaster Research',
    searchDisasterPlaceholder: base.searchDisasterPlaceholder || base.searchDisastersPlaceholder || 'Search historical disasters, events or locations (e.g., Cyclone Fani, Kerala Floods)...',
    compareNow: base.compareNow || base.compareEvents || 'Compare Events Now',
  };
}
